[package]
name = "yewssenger"
version = "0.1.0"
authors = ["nakta_theo"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
log = "0.4"
yew = "0.17"
wasm-bindgen = "0.2.67"
wasm-logger = "0.2"